version: '3.8'

services:
  frontend:
    container_name: astro-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: alejandrorojas073/astro-frontend:latest
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: express-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: alejandrorojas073/express-backend:latest
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://software:uiIOl2eMIwqgOIFZbd9Y0mWfeg9PpZ24@dpg-d0lbrrbuibrs73a61jsg-a.oregon-postgres.render.com/software_nfbg
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
